# Generated by Django 2.1.2 on 2018-11-17 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umarket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='userID',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='umarket.Profile'),
        ),
    ]
