# Generated by Django 2.1.2 on 2018-10-31 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umarket', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserAccount',
        ),
    ]
