# Generated by Django 2.1.2 on 2018-11-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umarket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, help_text='First name', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last name', max_length=20, null=True),
        ),
    ]
