# Generated by Django 2.1.2 on 2018-11-17 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umarket', '0002_auto_20181117_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='umarket.ProfileStruct'),
        ),
    ]
