# Generated by Django 2.1.2 on 2018-11-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umarket', '0003_auto_20181117_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category', max_length=100, unique=True)),
            ],
        ),
    ]
