# Generated by Django 2.1.2 on 2018-11-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umarket', '0005_auto_20181129_1333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
