# Generated by Django 2.1.2 on 2018-11-29 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umarket', '0008_auto_20181129_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='umarket.ProfileStruct'),
        ),
    ]
