# Generated by Django 2.1.2 on 2018-11-30 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umarket', '0012_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='favorited',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='umarket.ProfileStruct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_requests_created', to='umarket.ProfileStruct'),
        ),
    ]
